sync from SVN

diff --git a/trunk/src/Makefile.am b/trunk/src/Makefile.am
--- a/trunk/src/Makefile.am
+++ b/trunk/src/Makefile.am
@@ -46,7 +46,7 @@ host_os = @host_os@
 
 # common means common to the apl and libapl builds
 #
-common_CXXFLAGS = -Wall $(plot_CXXFLAGS) -I $(srcdir)/sql -I $(abs_top_srcdir) $(CXX_WERROR)
+common_CXXFLAGS = -Wall -O2 $(plot_CXXFLAGS) -I $(srcdir)/sql -I $(abs_top_srcdir) $(CXX_WERROR)
 common_CXXFLAGS += $(GTK_CFLAGS) $(GTK_LIBS)
 common_CXXFLAGS += $(PYTHON_CFLAGS)
 common_LDFLAGS  = -L/usr/local/lib -export-dynamic $(GTK_LDFLAGS)
@@ -165,6 +165,7 @@ common_SOURCES += RealCell.cc							RealCell.hh
 common_SOURCES += sbrk.cc
 common_SOURCES += Shape.cc					    		Shape.hh
 common_SOURCES += ScalarFunction.cc						ScalarFunction.hh
+common_SOURCES +=									ScalarOps.hh
 common_SOURCES += Security.cc		Security.def		Security.hh
 common_SOURCES += StateIndicator.cc						StateIndicator.hh
 common_SOURCES += Svar_DB.cc							Svar_DB.hh
@@ -315,8 +316,16 @@ testGTK: all
 
 # run all testcases, except slow ones
 test3: all
-	./apl --id 1010 -T testcases_3/*tc || true
-	stty sane
+	./apl --id 1010 -T testcases_3/*tc; \
+	RC=$$?; stty sane; \
+	if [ $$RC -ne 0 ]; then \
+	  D=/tmp/apl-test3-$$(date +%Y%m%d_%H%M%S); \
+	  mkdir "$$D"; \
+	  cp testcases_3/summary.log "$$D/"; \
+	  awk '$$1+0>0 && NF==4 {print $$4 ".log"}' testcases_3/summary.log \
+	    | xargs -r cp -t "$$D"; \
+	  echo "$(MAKE): $$RC failure(s) -- logs saved to $$D"; \
+	fi
 
 # run only invariant testcases
 test4: all
diff --git a/trunk/src/Makefile.in b/trunk/src/Makefile.in
--- a/trunk/src/Makefile.in
+++ b/trunk/src/Makefile.in
@@ -236,19 +236,19 @@ am__lib_gnu_apl_la_SOURCES_DIST = Plot_ascii.cc Plot_gtk.cc \
 	Quad_SQL.hh Quad_SVx.cc Quad_SVx.hh Quad_TF.cc Quad_TF.hh \
 	Quad_WA.cc Quad_WA.hh Quad_XML.cc Quad_XML.hh RealCell.cc \
 	RealCell.hh sbrk.cc Shape.cc Shape.hh ScalarFunction.cc \
-	ScalarFunction.hh Security.cc Security.def Security.hh \
-	StateIndicator.cc StateIndicator.hh Svar_DB.cc Svar_DB.hh \
-	Svar_record.cc Svar_record.hh tcp_signal.m4 Svar_signals.def \
-	Svar_signals.hh Symbol.cc Symbol.hh Simple_string.hh \
-	SymbolTable.cc SymbolTable.hh SystemLimits.def SystemLimits.hh \
-	Sys.cc Sys.hh SystemVariable.cc SystemVariable.def \
-	SystemVariable.hh TabExpansion.cc TabExpansion.hh \
-	Thread_context.cc Thread_context.hh Token.cc Token.def \
-	Token.hh Token_string.cc Token_string.hh TokenEnums.hh \
-	Tokenizer.cc Tokenizer.hh u8_string.hh UCS_string.cc \
-	UCS_string.hh UCS_string_vector.cc UCS_string_vector.hh \
-	Unicode.hh UserFunction.cc UserFunction.hh \
-	UserFunction_header.cc UserFunction_header.hh \
+	ScalarFunction.hh ScalarOps.hh Security.cc Security.def \
+	Security.hh StateIndicator.cc StateIndicator.hh Svar_DB.cc \
+	Svar_DB.hh Svar_record.cc Svar_record.hh tcp_signal.m4 \
+	Svar_signals.def Svar_signals.hh Symbol.cc Symbol.hh \
+	Simple_string.hh SymbolTable.cc SymbolTable.hh \
+	SystemLimits.def SystemLimits.hh Sys.cc Sys.hh \
+	SystemVariable.cc SystemVariable.def SystemVariable.hh \
+	TabExpansion.cc TabExpansion.hh Thread_context.cc \
+	Thread_context.hh Token.cc Token.def Token.hh Token_string.cc \
+	Token_string.hh TokenEnums.hh Tokenizer.cc Tokenizer.hh \
+	u8_string.hh UCS_string.cc UCS_string.hh UCS_string_vector.cc \
+	UCS_string_vector.hh Unicode.hh UserFunction.cc \
+	UserFunction.hh UserFunction_header.cc UserFunction_header.hh \
 	UserPreferences.cc UserPreferences.hh UTF8_string.cc \
 	UTF8_string.hh Ravel.cc Ravel.hh Value.cc Value.icc Value.hh \
 	cValue.cc Value_P.icc Value_P.hh ValueHistory.cc \
@@ -421,19 +421,19 @@ am__libapl_la_SOURCES_DIST = Plot_ascii.cc Plot_gtk.cc Plot_xcb.cc \
 	Quad_SQL.hh Quad_SVx.cc Quad_SVx.hh Quad_TF.cc Quad_TF.hh \
 	Quad_WA.cc Quad_WA.hh Quad_XML.cc Quad_XML.hh RealCell.cc \
 	RealCell.hh sbrk.cc Shape.cc Shape.hh ScalarFunction.cc \
-	ScalarFunction.hh Security.cc Security.def Security.hh \
-	StateIndicator.cc StateIndicator.hh Svar_DB.cc Svar_DB.hh \
-	Svar_record.cc Svar_record.hh tcp_signal.m4 Svar_signals.def \
-	Svar_signals.hh Symbol.cc Symbol.hh Simple_string.hh \
-	SymbolTable.cc SymbolTable.hh SystemLimits.def SystemLimits.hh \
-	Sys.cc Sys.hh SystemVariable.cc SystemVariable.def \
-	SystemVariable.hh TabExpansion.cc TabExpansion.hh \
-	Thread_context.cc Thread_context.hh Token.cc Token.def \
-	Token.hh Token_string.cc Token_string.hh TokenEnums.hh \
-	Tokenizer.cc Tokenizer.hh u8_string.hh UCS_string.cc \
-	UCS_string.hh UCS_string_vector.cc UCS_string_vector.hh \
-	Unicode.hh UserFunction.cc UserFunction.hh \
-	UserFunction_header.cc UserFunction_header.hh \
+	ScalarFunction.hh ScalarOps.hh Security.cc Security.def \
+	Security.hh StateIndicator.cc StateIndicator.hh Svar_DB.cc \
+	Svar_DB.hh Svar_record.cc Svar_record.hh tcp_signal.m4 \
+	Svar_signals.def Svar_signals.hh Symbol.cc Symbol.hh \
+	Simple_string.hh SymbolTable.cc SymbolTable.hh \
+	SystemLimits.def SystemLimits.hh Sys.cc Sys.hh \
+	SystemVariable.cc SystemVariable.def SystemVariable.hh \
+	TabExpansion.cc TabExpansion.hh Thread_context.cc \
+	Thread_context.hh Token.cc Token.def Token.hh Token_string.cc \
+	Token_string.hh TokenEnums.hh Tokenizer.cc Tokenizer.hh \
+	u8_string.hh UCS_string.cc UCS_string.hh UCS_string_vector.cc \
+	UCS_string_vector.hh Unicode.hh UserFunction.cc \
+	UserFunction.hh UserFunction_header.cc UserFunction_header.hh \
 	UserPreferences.cc UserPreferences.hh UTF8_string.cc \
 	UTF8_string.hh Ravel.cc Ravel.hh Value.cc Value.icc Value.hh \
 	cValue.cc Value_P.icc Value_P.hh ValueHistory.cc \
@@ -582,19 +582,19 @@ am__apl_SOURCES_DIST = main.cc Plot_ascii.cc Plot_gtk.cc Plot_xcb.cc \
 	Quad_SQL.hh Quad_SVx.cc Quad_SVx.hh Quad_TF.cc Quad_TF.hh \
 	Quad_WA.cc Quad_WA.hh Quad_XML.cc Quad_XML.hh RealCell.cc \
 	RealCell.hh sbrk.cc Shape.cc Shape.hh ScalarFunction.cc \
-	ScalarFunction.hh Security.cc Security.def Security.hh \
-	StateIndicator.cc StateIndicator.hh Svar_DB.cc Svar_DB.hh \
-	Svar_record.cc Svar_record.hh tcp_signal.m4 Svar_signals.def \
-	Svar_signals.hh Symbol.cc Symbol.hh Simple_string.hh \
-	SymbolTable.cc SymbolTable.hh SystemLimits.def SystemLimits.hh \
-	Sys.cc Sys.hh SystemVariable.cc SystemVariable.def \
-	SystemVariable.hh TabExpansion.cc TabExpansion.hh \
-	Thread_context.cc Thread_context.hh Token.cc Token.def \
-	Token.hh Token_string.cc Token_string.hh TokenEnums.hh \
-	Tokenizer.cc Tokenizer.hh u8_string.hh UCS_string.cc \
-	UCS_string.hh UCS_string_vector.cc UCS_string_vector.hh \
-	Unicode.hh UserFunction.cc UserFunction.hh \
-	UserFunction_header.cc UserFunction_header.hh \
+	ScalarFunction.hh ScalarOps.hh Security.cc Security.def \
+	Security.hh StateIndicator.cc StateIndicator.hh Svar_DB.cc \
+	Svar_DB.hh Svar_record.cc Svar_record.hh tcp_signal.m4 \
+	Svar_signals.def Svar_signals.hh Symbol.cc Symbol.hh \
+	Simple_string.hh SymbolTable.cc SymbolTable.hh \
+	SystemLimits.def SystemLimits.hh Sys.cc Sys.hh \
+	SystemVariable.cc SystemVariable.def SystemVariable.hh \
+	TabExpansion.cc TabExpansion.hh Thread_context.cc \
+	Thread_context.hh Token.cc Token.def Token.hh Token_string.cc \
+	Token_string.hh TokenEnums.hh Tokenizer.cc Tokenizer.hh \
+	u8_string.hh UCS_string.cc UCS_string.hh UCS_string_vector.cc \
+	UCS_string_vector.hh Unicode.hh UserFunction.cc \
+	UserFunction.hh UserFunction_header.cc UserFunction_header.hh \
 	UserPreferences.cc UserPreferences.hh UTF8_string.cc \
 	UTF8_string.hh Ravel.cc Ravel.hh Value.cc Value.icc Value.hh \
 	cValue.cc Value_P.icc Value_P.hh ValueHistory.cc \
@@ -1347,7 +1347,7 @@ DIST_SUBDIRS = $(SUBDIRS) testcases
 
 # common means common to the apl and libapl builds
 #
-common_CXXFLAGS = -Wall $(plot_CXXFLAGS) -I $(srcdir)/sql -I \
+common_CXXFLAGS = -Wall -O2 $(plot_CXXFLAGS) -I $(srcdir)/sql -I \
 	$(abs_top_srcdir) $(CXX_WERROR) $(GTK_CFLAGS) $(GTK_LIBS) \
 	$(PYTHON_CFLAGS) $(am__append_8) $(am__append_12)
 common_LDFLAGS = -L/usr/local/lib -export-dynamic $(GTK_LDFLAGS) \
@@ -1405,19 +1405,19 @@ common_SOURCES = $(plot_SOURCES) ../config.h APL_Float_as_class.hh \
 	Quad_SQL.hh Quad_SVx.cc Quad_SVx.hh Quad_TF.cc Quad_TF.hh \
 	Quad_WA.cc Quad_WA.hh Quad_XML.cc Quad_XML.hh RealCell.cc \
 	RealCell.hh sbrk.cc Shape.cc Shape.hh ScalarFunction.cc \
-	ScalarFunction.hh Security.cc Security.def Security.hh \
-	StateIndicator.cc StateIndicator.hh Svar_DB.cc Svar_DB.hh \
-	Svar_record.cc Svar_record.hh tcp_signal.m4 Svar_signals.def \
-	Svar_signals.hh Symbol.cc Symbol.hh Simple_string.hh \
-	SymbolTable.cc SymbolTable.hh SystemLimits.def SystemLimits.hh \
-	Sys.cc Sys.hh SystemVariable.cc SystemVariable.def \
-	SystemVariable.hh TabExpansion.cc TabExpansion.hh \
-	Thread_context.cc Thread_context.hh Token.cc Token.def \
-	Token.hh Token_string.cc Token_string.hh TokenEnums.hh \
-	Tokenizer.cc Tokenizer.hh u8_string.hh UCS_string.cc \
-	UCS_string.hh UCS_string_vector.cc UCS_string_vector.hh \
-	Unicode.hh UserFunction.cc UserFunction.hh \
-	UserFunction_header.cc UserFunction_header.hh \
+	ScalarFunction.hh ScalarOps.hh Security.cc Security.def \
+	Security.hh StateIndicator.cc StateIndicator.hh Svar_DB.cc \
+	Svar_DB.hh Svar_record.cc Svar_record.hh tcp_signal.m4 \
+	Svar_signals.def Svar_signals.hh Symbol.cc Symbol.hh \
+	Simple_string.hh SymbolTable.cc SymbolTable.hh \
+	SystemLimits.def SystemLimits.hh Sys.cc Sys.hh \
+	SystemVariable.cc SystemVariable.def SystemVariable.hh \
+	TabExpansion.cc TabExpansion.hh Thread_context.cc \
+	Thread_context.hh Token.cc Token.def Token.hh Token_string.cc \
+	Token_string.hh TokenEnums.hh Tokenizer.cc Tokenizer.hh \
+	u8_string.hh UCS_string.cc UCS_string.hh UCS_string_vector.cc \
+	UCS_string_vector.hh Unicode.hh UserFunction.cc \
+	UserFunction.hh UserFunction_header.cc UserFunction_header.hh \
 	UserPreferences.cc UserPreferences.hh UTF8_string.cc \
 	UTF8_string.hh Ravel.cc Ravel.hh Value.cc Value.icc Value.hh \
 	cValue.cc Value_P.icc Value_P.hh ValueHistory.cc \
@@ -6985,8 +6985,16 @@ testGTK: all
 
 # run all testcases, except slow ones
 test3: all
-	./apl --id 1010 -T testcases_3/*tc || true
-	stty sane
+	./apl --id 1010 -T testcases_3/*tc; \
+	RC=$$?; stty sane; \
+	if [ $$RC -ne 0 ]; then \
+	  D=/tmp/apl-test3-$$(date +%Y%m%d_%H%M%S); \
+	  mkdir "$$D"; \
+	  cp testcases_3/summary.log "$$D/"; \
+	  awk '$$1+0>0 && NF==4 {print $$4 ".log"}' testcases_3/summary.log \
+	    | xargs -r cp -t "$$D"; \
+	  echo "$(MAKE): $$RC failure(s) -- logs saved to $$D"; \
+	fi
 
 # run only invariant testcases
 test4: all
